#!/usr/bin/env python3
# Round-4: compact the Summary (abstract) to <=300 words (was 329).
F = "I_正文_IMRaD_en.md"
s = open(F, encoding="utf-8").read()

old = ("**Introduction.** Hyperalgesia after remifentanil infusion has generated a substantial prevention literature, yet the clinical evidence remains contested and real-world reporting is unassessed.\n\n"
"**Methods.** Disproportionality analysis in two national databases: the United States Food and Drug Administration Adverse Event Reporting System (20 692 687 reports) as the primary analysis and the Health Canada Canada Vigilance line-listing (1 154 017 reports, to 30 November 2024) for confirmation; cohorts were remifentanil, fentanyl, sufentanil and morphine. Reporting odds ratios, proportional reporting ratios, information components and empirical Bayes geometric means were computed for the terms defined a priori. Because a term returns a count only if it is a preferred term, every term was verified as retrievable in both databases before any zero was read; the proxies were added after those zeros, dated in the plan, because the two prespecified hyperalgesia terms (HYPERALGESIA, ALLODYNIA) were non-estimable, so the analysis became hypothesis-generating and the proxies are reported as exploratory. Signals required at least three reports with a lower confidence bound above one; remifentanil was compared with each comparator by the ratio of reporting odds ratios.\n\n"
"**Results.** The word used in clinical practice for the syndrome is not a preferred term in either dictionary and returned no report, whereas the preferred term carrying it was present in both (8 161; 523) and met the signal criterion for all four opioids, remifentanil included (4.73, 2.54–8.80), but the signal rests on ten reports, eight in 2024, and disappears when 2024 is excluded (a = 1); it did not reproduce. For pain, remifentanil reported least of the four and every computable head-to-head ratio was below one (0.066, 95% confidence interval 0.04–0.10, versus fentanyl; 0.046 versus morphine; 0.235 and 0.146 in Canada). The same direction held for every negative control, on serious-report restriction, and in each of the eight estimable years.\n\n"
"**Discussion.** The answer depended on the term chosen, so such an analysis is hypothesis-generating at best, and a zero from the clinical name alone is not evidence of safety.")

new = ("**Introduction.** Hyperalgesia after remifentanil infusion has generated a substantial prevention literature, yet the clinical evidence is contested and real-world reporting is unassessed.\n\n"
"**Methods.** Disproportionality analysis in two national databases: the United States Food and Drug Administration Adverse Event Reporting System (20 692 687 reports) as primary and the Health Canada Canada Vigilance line-listing (1 154 017 reports) for confirmation; cohorts were remifentanil, fentanyl, sufentanil and morphine. Reporting odds ratios, proportional reporting ratios, information components and empirical Bayes geometric means were computed for a priori terms. Because a count requires a preferred term, every term was verified retrievable in both databases before any zero was read; the two prespecified hyperalgesia terms were non-estimable, so the analysis became hypothesis-generating and five dictionary proxies added after those zeros, dated in the plan, are reported as exploratory. Signals required at least three reports with a lower confidence bound above one; remifentanil was compared with each comparator by the ratio of reporting odds ratios.\n\n"
"**Results.** The clinical word is not a preferred term in either dictionary and returned no report, whereas the preferred term carrying it was present in both (8 161; 523) and met the signal criterion for all four opioids, remifentanil included (4.73, 2.54–8.80), but the signal rests on ten reports, eight in 2024, and disappears when 2024 is excluded (a = 1); it did not reproduce. For pain, remifentanil reported least of the four and every computable head-to-head ratio was below one (0.066, 95% CI 0.04–0.10, versus fentanyl; 0.046 versus morphine; 0.235 and 0.146 in Canada). The same direction held for every negative control, on serious-report restriction, and in each of the eight estimable years.\n\n"
"**Discussion.** The answer depended on the term chosen, so the analysis is hypothesis-generating, and a zero from the clinical name alone is not evidence of safety.")

n = s.count(old)
assert n == 1, f"abstract block count={n}"
s = s.replace(old, new, 1)
open(F, "w", encoding="utf-8").write(s)
print("Abstract compacted OK")
