#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
soc_rules.py — PT -> 27 个标准 MedDRA SOC 的规则字典（单一事实源）

设计
----
* 27 行 = MedDRA 标准 SOC 全集（含 Investigations；Cardiac 与 Vascular 分列）。
* 匹配方式：关键词**子串**匹配；**规则列表顺序 = 优先级**，首个命中即返回。
* 顺序原则：先"检验/测量类"（Investigations —— MedDRA 把 Blood pressure / Heart rate /
  Haemoglobin / Transaminases / Blood creatinine 等归此），再具体器官 SOC，最后宽泛 SOC
  （Product issues -> General -> Social）。
* 局限（须在正文披露）：这是**规则法**近似映射，不是官方 MedDRA 字典。
  一个 PT 只归首个命中 SOC；未命中者记为 Unmapped，不计入任何 SOC。

版本 v4（2026-09-13）：
  - 由 v3（25 条；Cardiac/Vascular 合并、缺 Investigations）升级为 27 条标准 SOC；
  - 新增 Investigations，并把散落在器官 SOC 里的检验类 PT 归位；
  - 拆分 Cardiac disorders / Vascular disorders。
"""

# ============================ 27 SOC 规则（顺序=优先级） ============================
SOC_RULES = [
 # ---------------- 1. 检验与测量（须最先，否则被器官 SOC 抢走） ----------------
 ("Investigations",
   ["BLOOD CREATININE","BLOOD UREA","GLOMERULAR FILTRATION","RENAL CLEARANCE",
    "LIVER FUNCTION","HEPATIC ENZYME","TRANSAMINASE","ALANINE AMINOTRANSFERASE","ASPARTATE AMINOTRANSFERASE",
    "ALKALINE PHOSPHATASE","GAMMA-GLUTAMYL","BLOOD BILIRUBIN","BILIRUBIN",
    "HAEMOGLOBIN","HEMOGLOBIN","HAEMATOCRIT","HEMATOCRIT","MEAN CELL VOLUME","MEAN CELL HAEMOGLOBIN",
    "PLATELET COUNT","WHITE BLOOD CELL","RED BLOOD CELL","NEUTROPHIL COUNT","EOSINOPHIL COUNT","MONOCYTE COUNT",
    "LYMPHOCYTE COUNT","BASOPHIL COUNT","RETICULOCYTE","ERYTHROCYTE","LEUCOCYTE","BLOOD FIBRINOGEN","BLOOD COUNT",
    "BLOOD GLUCOSE","GLYCATED HAEMOGLOBIN","BLOOD LACTATE","BLOOD PH","BLOOD GASES",
    "BLOOD SODIUM","BLOOD POTASSIUM","BLOOD CALCIUM","BLOOD MAGNESIUM","BLOOD CHLORIDE","BLOOD PHOSPHORUS",
    "BLOOD ALBUMIN","TOTAL PROTEIN","C-REACTIVE PROTEIN","ERYTHROCYTE SEDIMENTATION",
    "PROTHROMBIN TIME","PARTIAL THROMBOPLASTIN","INR","COAGULATION TIME",
    "BLOOD PRESSURE","HEART RATE","OXYGEN SATURATION","RESPIRATORY RATE","BODY TEMPERATURE",
    "ELECTROCARDIOGRAM","EJECTION FRACTION","TROPONIN","CARDIAC FUNCTION","LUNG FUNCTION","PULMONARY FUNCTION",
    "CREATINE PHOSPHOKINASE","CREATINE KINASE","BODY MASS INDEX","WEIGHT","DRUG LEVEL","TOXICOLOGY",
    "VIRAL TEST","SEROLOGY","CULTURE","LABORATORY TEST","TEST ABNORMAL","ELECTROENCEPHALOGRAM",
    "BLOOD CHOLESTEROL","OLIGOCLONAL","ANTINUCLEAR","PLEOCYTOSIS","LEUKOCYTOSIS"]),

 # ---------------- 2. 免疫（须早于 Vascular，避免 ANAPHYLACTIC SHOCK 被 SHOCK 抢走） ----------------
 ("Immune system disorders",
   ["ANAPHYLAXIS","ANAPHYLACTIC","ANAPHYLACTOID","HYPERSENSITIV","HYPERSENSITIVITY","ALLERGIC","ALLERGY","ALLERG",
    "IMMUNE","IMMUNOLOGICAL","IMMUNOSUPPRESS","AUTOIMMUNE","CYTOLYTIC","SERUM SICKNESS","DRUG HYPERSENSITIVITY",
    "TYPE III","TYPE II","CYTOKINE RELEASE","EOSINOPHILIA AND SYSTEMIC","IMMUNODEFICIENCY"]),

 # ---------------- 3. 精神类 ----------------
 ("Psychiatric disorders",
   ["DISSOCIAT","HALLUCINAT","SUICID","SELF-INJUR","SUICIDE","ABUSE","DEPEND","EUPHOR","CONFUS","DISORIENT",
    "ABNORMAL BEHAVIOUR","THOUGHT","THINKING","ANXIET","PANIC","INSOMN","AGITAT","DEPRESS","IMPULS","MOOD","HOSTIL","ANGER",
    "IRRITAB","RESTLESS","MENTAL STATUS","MENTAL DISORDER","MENTAL IMPAIRMENT","PSYCHOS","DELIR","HOMICID","WITHDRAW",
    "CRAVING","TOLERAN","SCHIZOPHREN","BIPOLAR","OBSESS","EATING DISORDER","DISSOCIATIVE","AMNESIA","SLEEP DISORDER",
    "NIGHTMARE","LIBIDO","MANIA","EMOTIONAL DISTRESS","CRYING","AGGRESS","DELUSION","PARANOIA","AFFECT LABILITY",
    "PSYCHOMOTOR","DEREALIS","HYPERSOMNI","ATTENTION","NERVOUSNESS","ILLUSION","STRESS",
    "PSYCHOT","EMOTIONAL DISORDER","ANHEDONIA","AUTOSCOPY","SEROTONIN","DRUG USE DISORDER","BEHAVIOUR DISORDER",
    "AKATHISIA","APATHY","DYSPHORIA","CATATONIA","CONVERSION DISORDER","PSYCHIATRIC SYMPTOM","FEELING OF DESPAIR",
    "ABNORMAL DREAMS","AFFECTIVE DISORDER","LOGORRHOEA","FEAR","INCOHERENT"]),

 # ---------------- 4. 神经系统 ----------------
 ("Nervous system disorders",
   ["SEIZURE","CONVULS","SOMNOLEN","DIZZIN","HEADACH","LOSS OF CONSCIOUSNESS","ALTERED STATE OF CONSCIOUSNESS",
    "PARAESTH","PARESTH","HYPERAESTH","HYPERESTH","NEUROPATH","TREMOR","DYSKINES","MYOCLON","ATAXIA","SYNCOP",
    "HYPERREFLEX","NUMBNESS","ENCEPHAL","STUPOR","COMA","HYPOTON","PARALYS","SPEECH","MEMORY","COGNITIVE","AMNESIA",
    "LETHARG","UNRESPONS","NEURALG","RESTLESS LEG","MYOPATHY","PARKINSON","DYSTONIA","NEUROLOGIC","CEREBRAL","BRAIN",
    "SPINAL","MENING","CONVULSIVE","STATUS EPILEPTICUS","HYPOREFLEXIA","SEDATION","HYPOAESTHESIA","HYPOESTHESIA",
    "MIGRAINE","DYSARTHRIA","GAIT DISTURBANCE","FEELING DRUNK","MENINGISM","TASTE","AGEUSIA","SENSORY DISTURBANCE",
    "NERVOUS SYSTEM","BALANCE","HYPOKINESI","MULTIPLE SCLEROSIS","GAIT","NERVE",
    "MOVEMENT DISORDER","DEMENTIA","DYSSTASIA","EPILEP","APHASIA","PARESIS","NEUROLEPTIC MALIGNANT"]),

 # ---------------- 5. 心脏 ----------------
 ("Cardiac disorders",
   ["CARDIAC","MYOCARDIAL","TACHYCARD","BRADYCARD","ARRHYTHM","ATRIAL","VENTRICULAR","ANGINA","CARDIOMYOPATH",
    "HEART FAILURE","PALPITAT","VALVULAR","PERICARD","MYOCARDIT","CARDIOGENIC","CORONARY","CARDIO","SINUS ARREST",
    "SINUS BRADYCARDIA","SUPRAVENTRICULAR","ATRIOVENTRICULAR","HEART DISORDER","CARDIOMEGALY"]),

 # ---------------- 6. 血管 ----------------
 ("Vascular disorders",
   ["HYPERTENS","HYPOTENS","CIRCULATORY COLLAPSE","THROMBOS","EMBOL","ISCHAEM","ISCHEM","HAEMORRHAGE","HEMORRHAGE",
    "PETECH","THROMBOPHLEBIT","VASODILAT","SHOCK","AORTIC","ATHEROSCLER","PHLEBIT","VARICOSE","VENOUS","VASCUL",
    "PULSE","OEDEMA PERIPHERAL","PERIPHERAL OEDEMA","HAEMATOMA","HEMATOMA","ECCHYMOS","CONTUSION","BLOOD LOSS",
    "INTRACRANIAL HAEMORRHAGE","SUBARACHNOID","SUBDURAL","PULMONARY EMBOL","DEEP VEIN","CEREBROVASCULAR",
    "TRANSIENT ISCHAEMIC","HAEMORRHOID","HEMORRHOID","HAEMODYNAMIC","HEMODYNAMIC","FLUSHING","HOT FLUSH","ORTHOSTATIC",
    "PALLOR","VASOPLEGIA","HYPOPERFUSION","PERIPHERAL COLDNESS","LYMPHOEDEMA"]),

 # ---------------- 7. 呼吸 ----------------
 ("Respiratory, thoracic and mediastinal disorders",
   ["RESPIRAT","APNOE","APNEA","HYPOX","DYSPL","DYSPN","PNEUMON","BRONCHO","LARYNG","COUGH","PULMONAR","THROAT",
    "CHOKING","SUFFOCAT","AIRWAY","EPISTAX","NASAL","RHINIT","HYPERVENTIL","PULMONARY OEDEMA","ASPHYX","CHEST CONGEST",
    "PHARYNGEAL","SNORING","SLEEP APNOEA","PLEURAL","BRONCHITIS","TRACHEAL","LARYNGEAL","OROPHARYNGEAL","RESPIRATORY",
    "HICCUPS","EXPECTORAT","HAEMOPTYSIS","SINUSITIS","LARYNX","PHRENIC","MEDIASTINAL","ASTHMA","INSPIRATORY","WHEEZ",
    "RHINORRHOEA","PRODUCTIVE COUGH","DYSPHONIA","PNEUMOTHORAX","LUNG DISORDER",
    "LUNG DISEASE","EMPHYSEMA","HAEMOTHORAX","TACHYPNOEA","SNEEZING","SINUS DISORDER",
    "HYPERCAPNIA","ASPIRATION"]),

 # ---------------- 8. 肾脏与泌尿 ----------------
 ("Renal and urinary disorders",
   ["CYSTIT","DYSUR","HAEMATUR","HEMATUR","URINARY","BLADDER","KIDNEY","RENAL","NEPHR","URETER","URETHR","OLIGUR",
    "ANUR","POLYUR","PROTEINUR","NEPHROLITH","URAEM","URAMIA","CALCULI","GLOMERULONEPHR","VESICOURINARY","UROLITH",
    "PYELONEPHR","NEPHROTIC","UROLOGIC","HYDRONEPHROS","NEPHRECTOMY","HYDRONEPHRO","RENAL COLIC",
    "POLLAKIURIA","NOCTURIA","MICTURITION","URINARY RETENTION","DYSURIA","BLADDER PAIN","DIALYSIS"]),

 # ---------------- 9. 胃肠 ----------------
 ("Gastrointestinal disorders",
   ["NAUSEA","NAUSE","VOMIT","DIARRHOE","DIARRHEA","DIARR","ABDOMINAL PAIN","ABDOMINAL","ABDOMEN","CONSTIPAT",
    "GASTROENTERITIS","INTESTIN","RECTAL","RECTUM","ANOREXIA","DYSPEPS","DYSPEP","FLATULEN","REGURGITAT","PANCREATITIS",
    "COLITIS","ORAL","SALIVARY","DROOLING","GASTRITIS","GASTRO","DYSGEUS","DRY MOUTH","HAEMATEMES","MELAENA","PROCTALG",
    "TENESMUS","STOMACH","BOWEL","APPENDICITIS","ILEUS","PERITONITIS","ABDOMINAL DISTENSION","HERNIA","HAEMATOSIA",
    "GINGIVAL","DYSPHAG","GASTROOE","OESOPHAG","ESOPHAG","ENTERITIS","DUODEN","PEPTIC","ULCER","GASTR",
    "STOMATITIS","APHTHOUS","ORAL MUCOSAL","GASTROINTESTINAL","CROHN","ANAL ","HAEMATOCHEZIA","FAECAL","DIVERTICUL",
    "IRRITABLE BOWEL","TOOTH","HYPERSALIVATION","SIALORRHOEA","SIALORRHEA","SALIVATION",
    "GLOSSODYNIA","GLOSSITIS","HEARTBURN","ASCITES"]),

 # ---------------- 10. 肝胆 ----------------
 ("Hepatobiliary disorders",
   ["HEPATITIS","HEPATIT","JAUNDICE","JAUND","CHOLESTAS","CHOLESTATIC","LIVER FAILURE","HEPATIC","LIVER","BILIARY",
    "CIRRHOSIS","HEPATOTOXIC","HEPATORENAL","BILE","HEPAT","CHOLELITH","CHOLANGITIS","LIVER INJURY","HEPATIC INJURY",
    "CHOLECYSTITIS"]),

 # ---------------- 11. 皮肤 ----------------
 ("Skin and subcutaneous tissue disorders",
   ["RASH","ERUPTION","PRURITUS","URTICAR","ANGIOEDEMA","DERMATITIS","EXANTHEMA","SKIN","ACNE","ALOPECIA",
    "HYPERHIDROS","PHOTOSENS","STEVENS JOHNSON","TOXIC EPIDERMAL","ERYTHEMA MULTIFORME","ECZEMA",
    "HYPERSENSITIVITY RASH","BLISTER","DERMATOLOG","NAIL","SWEATING","COLD SWEAT","CUTANEOUS","DERMAL","ERYTHEMA",
    "ERYTHEMATOUS","DRUG ERUPTION","BULLA","PEMPHIGUS","PSORIASIS","SKIN DISORDER","HYPERPIGMENT","SKIN REACTION",
    "PUSTUL","NODULE","STEVENS-JOHNSON","NIGHT SWEATS","PALMAR-PLANTAR"]),

 # ---------------- 12. 眼 ----------------
 ("Eye disorders",
   ["VISUAL","VISION","EYE","OCULAR","BLURRED","CONJUNCTIVITIS","GLAUCOMA","RETINAL","BLIND","DIPLOPIA","LACRIMAT",
    "OPTIC","OCULOGYRIC","VITREOUS","CORNEAL","UVEITIS","SCLERAL","EYELID","PTOSIS","MYDRIASIS",
    "ACCOMMODATION","OCUL","XEROPHTHAL","BLEPHAR","CATARACT","NYSTAGMUS","OPHTHALM","KERATITIS",
    "PHOTOPHOBIA","PAPILLOEDEMA","MACULOPATH","RETINOPATH","MIOSIS"]),

 # ---------------- 13. 耳与迷路 ----------------
 ("Ear and labyrinth disorders",
   ["EAR","HEARING","TINNITUS","TINNIT","VERTIGO","DEAF","OTOTOXIC","VESTIBULAR","VESTIB","ACOUSTIC","HYPACUSIS",
    "HYPOACUSIS","HYPERACUSIS","EUSTACHIAN","LABYRINTH","AUDITORY","PRESBYCUSIS","OTITIS"]),

 # ---------------- 14. 肌肉骨骼 ----------------
 ("Musculoskeletal and connective tissue disorders",
   ["ARTHRALGIA","MYALGIA","MUSCLE","MUSCUL","MUSCULAR","BONE","OSTEO","TENDON","TENDINITIS","RHEUMATISM","BACK PAIN",
    "NECK PAIN","JOINT","CARTILAGE","RICKETS","RHABDOMYOLYSIS","SOFT TISSUE","TETANY","MUSCULOSKELETAL","SPONDYL",
    "SCOLIOSIS","KYPHOSIS","BURSA","MYOSITIS","FIBROMYALGIA","OSTEOARTHRITIS","ARTHRITIS","ARTHROPATH","DISC",
    "CHONDRO","SYNOV","LIGAMENT","CRAMP","MUSCLE SPASM","MOBILITY DECREASED","BONE PAIN","MUSCLE PAIN","JOINT PAIN",
    "DEFORMITY","HYPERTONIA"]),

 # ---------------- 15. 血液与淋巴 ----------------
 ("Blood and lymphatic system disorders",
   ["ANAEMIA","ANEMIA","LEUKOPENIA","THROMBOCYTOPENIA","NEUTROPENIA","PANCYTOPENIA","LYMPHOPENIA","COAGULOPATHY",
    "COAGUL","HAEMOLYSIS","HEMOLYSIS","LYMPHADENOPATHY","SPLENOMEGALY","THROMBOCYTHAEMIA","POLYCYTHAEMIA",
    "HAEMATOPOIESIS","LEUKAEMOID","PLASMA CELL","CLOTTING","BLOOD DISORDER","HAEMATOLOGICAL","THROMBOCYT","PURPURA",
    "PETECHIAE","BONE MARROW FAILURE","AUTOIMMUNE HAEMOLYTIC","HAEMATOLYTIC","MYELOSUPPRESS","BONE MARROW"]),

 # ---------------- 16. 内分泌 ----------------
 ("Endocrine disorders",
   ["THYROID","THYROIDITIS","ADRENAL","ADRENOCORTICAL","HYPERGLYCAEMIA","HYPOGLYCAEMIA","HYPERGLYCAEMIC","HYPOGLYC",
    "HYPERGLYC","DIABETES","PITUITARY","PITUIT","PARATHYROID","CUSHING","SIADH","GROWTH HORMONE","HYPERTHYROID",
    "HYPOTHYROID","PANCREATIC","ENDOCRINE","GONADAL","HYPOPITUITARY","ACROMEGALY"]),

 # ---------------- 17. 肿瘤（前置于生殖：避免 BREAST/PROSTATE/CERVICAL CANCER 被生殖 SOC 截留） ----------------
 ("Neoplasms benign, malignant and unspecified",
   ["CANCER","NEOPLASM","NEOPLASIA","NEOPLASTIC","TUMOUR","TUMOR","CARCINOMA","CARCINOM","LEUKAEMIA","LEUKEMIA",
    "LYMPHOMA","METASTASIS","MALIGNANT","MALIGNANCY","MYELOMA","SARCOMA","ADENOMA","BENIGN","PREMALIGNANT",
    "MYELOPROLIFERATIVE","LYMPHOPROLIFERATIVE","BLAST","HODGKIN","BURKITT","ONCOLOGY","MYELODYSPLASTIC"]),

 # ---------------- 18. 生殖与乳腺 ----------------
 ("Reproductive system and breast disorders",
   ["MENSTRUAL","OVARIAN","UTERINE","UTERUS","VAGINAL","VAGINA","BREAST","PENILE","PENIS","TESTICULAR","TESTIS",
    "PROSTATIC","PROSTATE","ERECTILE","SEXUAL","GYNECOMASTIA","GYNAECOMASTIA","MAMMARY","CERVICAL","ENDOMETRIAL",
    "ENDOMETRIOSIS","SEMEN","OVULATION","FERTILITY","IMPOTENCE","EJACULATION","PROLACTIN","PELVIC","VULVOVAGINAL",
    "VULVOVAGINITIS","MENOPAUSE","SCROTAL","ANORGASMIA"]),

 # ---------------- 19. 妊娠与围产期 ----------------
 ("Pregnancy, puerperium and perinatal conditions",
   ["PREGNAN","FOETAL","FETAL","NEONAT","ABORTION","STILLBIRTH","TERATOGEN","PLACENTAL","PLACENT","OBSTETRIC",
    "LABOUR","PUERPERIUM","BREASTFEEDING","INTRAUTERINE","EMBRYO","OLIGOHYDRAMNIOS","PREMATURE",
    "POSTPARTUM","PREECLAMPSIA","ECTOPIC","AMNIOTIC","PERINATAL","NEWBORN","INFANT"]),

 # ---------------- 20. 损伤/中毒/操作并发症 ----------------
 ("Injury, poisoning and procedural complications",
   ["FALL","FRACTURE","LACERATION","LACERATED","POST PROCEDURE","PROCEDURE","INJURY","TRAUMA","WOUND","BURN",
    "OVERDOSE","CONCUSSION","SPRAIN","STRAIN","INJURED","COMPRESSION","ASPHYXIAL","DROWNING","POISONING",
    "FOREIGN BODY","MECHANICAL","OCCUPATIONAL","SUICIDE ATTEMPT","COMPLETED SUICIDE","OFF LABEL","DRUG INEFFECTIVE",
    "SUBSTANCE","INTOXICATION","TRAUMATIC","BLUNT","PENETRATING","BITE","ELECTRIC","THERMAL","IRRITATION","ABRASION",
    "HAEMORRHAGIC","INTERNAL INJURY","TOXICITY TO VARIOUS AGENTS","DRUG INTERACTION","INCORRECT DOSE","UNDERDOSE",
    "ACCIDENTAL EXPOSURE","INTENTIONAL","ACCIDENT","ROAD TRAFFIC","MECHANISM OF INJURY",
    "EXTRA DOSE","IMPAIRED HEALING"]),

 # ---------------- 21. 感染 ----------------
 ("Infections and infestations",
   ["INFECTION","INFECT","SEPSIS","SEPTIC","SEPTICAEMIA","INFLUENZA","CELLULITIS","ABSCESS","TUBERCULOSIS","VIRAL",
    "BACTERIAL","BACTERAEMIA","FUNGAL","FUNGUS","FUNGAEMIA","VIRAEMIA","MENINGITIS","ENDOCARDITIS","HERPES","COVID",
    "GASTROENTERITIS","PYELONEPHRITIS","VIRUS","BACTERIUM","MYCOSIS","OPPORTUNISTIC","INFESTATION","PARASIT",
    "PYOGENIC","NASOPHARYNGITIS","MULTIPLE-DRUG RESISTANCE","TINEA","CANDIDIASIS","SARS-COV-2","MYCOPLASMA"]),

 # ---------------- 22. 手术与医疗操作 ----------------
 ("Surgical and medical procedures",
   ["SURGERY","SURGICAL","OPERATION","OPERATIVE","BIOPSY","TRANSFUSION","INTUBATION","VENTILATION","ANAESTHESIA",
    "ANAESTHETIC","CATHETER","STENT","IMPLANT","RADIOTHERAPY","CHEMOTHERAPY","TRACHEOSTOMY","CAESAREAN","ENDOSCOPY",
    "AMPUTATION","DEBRIDEMENT","DRAIN","MEDICAL DEVICE","PROSTHESIS","PRE-PROCEDURE","POST-PROCEDURE",
    "CARDIOVERSION","EMBOLISATION","IRRIGATION","CANNULATION","VENESECTION","SUTURE","GASTROSTOMY","INVASIVE",
    "PROCEDURAL","SURG","ARTHROPLASTY","REHABILITATION"]),

 # ---------------- 23. 先天/家族/遗传 ----------------
 ("Congenital, familial and genetic disorders",
   ["CONGENITAL","FAMILIAL","GENETIC","HEREDITARY","HEREDIT","BIRTH DEFECT","TRISOMY","MALFORMATION","DEVELOPMENTAL",
    "INBORN","ANCESTRY","MARFAN","DOWN SYNDROME","TURNER","KLINEFELTER","GENETIC MUTATION","MUTATION"]),

 # ---------------- 24. 代谢与营养 ----------------
 ("Metabolism and nutrition disorders",
   ["HYPOKALAEMIA","HYPERNATRAEMIA","HYPONATRAEMIA","HYPERNATR","HYPONATR","DEHYDRATION","DEHYDRAT","HYPOMAGNESAEMIA",
    "HYPOCALCAEMIA","HYPOCALC","HYPERCALCAEMIA","HYPERCALC","ACIDOSIS","ALKALOSIS","HYPERKALEMIA","HYPERKAL",
    "HYPOKAL","NUTRITION","NUTRITIONAL","APPETITE","KETOACIDOSIS","KETOSIS","HYPERLIPIDAEMIA","HYPOPHOSPHATAEMIA",
    "MALNUTRITION","MALNUTRI","VITAMIN","HYPERURICAEMIA","ELECTROLYTE","OSMOLALITY","METABOL","METABOLIC","CACHEXIA",
    "PROTEIN","HYPOPROTEINAEMIA","LACTIC ACIDOSIS","LACTIC ACID","REFEEDING","FLUID OVERLOAD","HYPOVOLAEMIA",
    "HYPERVOLAEMIA","HUNGER","CHOLESTEROLAEMIA","DYSLIPIDAEMIA","THIRST","FEEDING DISORDER","HYPOPHAGIA"]),

 # ---------------- 25. 产品问题 ----------------
 ("Product issues",
   ["PRODUCT","DEVICE","LABEL","MEDICATION ERROR","DRUG ADMINISTRATION ERROR","WRONG","DOSE ERROR","COUNTERFEIT",
    "EXPIRY","STORAGE","PACKAGING","DEFECTIVE","SUBSTITUTION","QUALITY","MANUFACTURING","LOT","MEDICINAL","RECALL",
    "DOSE OMISSION","THERAPEUTIC","NON-RESPONDER","RESPONDER","TREATMENT FAILURE","THERAPY INTERRUPTED",
    "THERAPY CESSATION","UNKNOWN INDICATION","UNAPPROVED INDICATION","PRODUCT USE ISSUE","OFF LABEL USE","INADEQUATE",
    "POOR COMPLIANCE","DRUG RESISTANCE","PARADOXICAL","NEEDLE ISSUE","SYRINGE ISSUE","DRUG EFFECT LESS",
    "DELIVERY SYSTEM","DELIVERY MECHANISM","PRODUCT DELIVERY","DRUG DELIVERY","DEVICE DELIVERY"]),

 # ---------------- 26. 全身性/给药部位 ----------------
 ("General disorders and administration site conditions",
   ["PYREXIA","FEVER","FATIGUE","ASTHENIA","ASTHENIC","MALAISE","CHILLS","PAIN","INJECTION","INFUSION","EXTRAVASATION",
    "SITE REACTION","INDURATION","SWELLING","FEELING ABNORMAL","CHEST PAIN","WEAKNESS","LOCAL SWELLING",
    "INFLUENZA LIKE","DEATH","GENERAL PHYSICAL","ACHE","DISCOMFORT","PROSTRATION","CONDITION AGGRAVATED",
    "DISEASE PROGRESSION","DISEASE RECURRENCE","ILLNESS","FLUID RETENTION","UNWELL","GENERALISED","ADVERSE EVENT",
    "ADVERSE DRUG REACTION","ORGAN DYSFUNCTION","SUDDEN DEATH","ILL-DEFINED DISORDER","FEELING HOT","UNEVALUABLE",
    "OEDEMA","PYREXIAL","INFLAMMATION","FEELING COLD","HYPERTHERMIA",
    "SYSTEMIC INFLAMMATORY RESPONSE","ADVERSE REACTION"]),

 # ---------------- 27. 社会状况 ----------------
 ("Social circumstances",
   ["HOMELESS","UNEMPLOYED","INCARCERATION","LEGAL","SOCIAL","CRIMINAL","HOUSING","FINANCIAL","WIDOWED","VICTIM",
    "ALCOHOL ABUSE","ALCOHOL","DIVORCED","RETIREMENT","OCCUPATION","ILLITERATE","UNINSURED","PENAL","DETENTION",
    "PROBATION","SOCIETAL","TREATMENT NONCOMPLIANCE","IMPAIRED WORK ABILITY","HOSPITALISATION","WORK ABILITY",
    "INSURANCE ISSUE"]),
]

SOC_LIST = [name for name, _ in SOC_RULES]
SOC_INDEX = {name: i for i, name in enumerate(SOC_LIST)}
NSOC = len(SOC_RULES)


def map_soc(pt):
    """返回 PT 所属 SOC 名；未命中返回 None。首个命中生效。

    匹配规则：关键词必须落在**词首边界**（PT 开头，或前一个字符非字母数字）。
    这样既保留前缀语义（DISSOCIAT 命中 DISSOCIATION/DISSOCIATIVE），
    又杜绝词中误命中这类系统性污染：
        LIVER ⊄ DE▸LIVER◂Y（否则所有 DELIVERY* 被误判肝胆）
        EAR   ⊄ F▸EAR◂ / H▸EAR◂ING
        INR   ⊄ SP▸INR◂AZA
    """
    u = pt.upper()
    for soc, kws in SOC_RULES:
        for kw in kws:
            if not kw:
                continue
            i = u.find(kw)
            while i != -1:
                if i == 0 or not u[i-1].isalnum():
                    return soc
                i = u.find(kw, i + 1)
    return None


if __name__ == "__main__":
    print(f"SOC 数量 = {NSOC}")
    for i, n in enumerate(SOC_LIST, 1):
        print(f"  {i:2d}. {n}")
    probe = ["DISSOCIATION","SUICIDAL IDEATION","RESPIRATORY FAILURE","SEDATION","CYSTITIS","ACUTE KIDNEY INJURY",
             "BLOOD CREATININE INCREASED","ALANINE AMINOTRANSFERASE INCREASED","BLOOD PRESSURE DECREASED",
             "HEART RATE INCREASED","PRODUCT USE IN UNAPPROVED INDICATION","DEVICE FAILURE","SEROTONIN SYNDROME",
             "ANAPHYLACTIC SHOCK","PULMONARY EMBOLISM","CARDIAC ARREST","HAEMOGLOBIN DECREASED","THROMBOCYTOPENIA",
             "GAIT DISTURBANCE","EMOTIONAL DISTRESS","NASOPHARYNGITIS","TOXICITY TO VARIOUS AGENTS","SOMETHINGWEIRD"]
    print("\n-- probe --")
    for t in probe:
        print(f"  {t:44s} -> {map_soc(t)}")
